using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using SoulsFormats;
using System.Numerics;

public class MSBSUnkStruct1Part : MonoBehaviour
{
    public byte Condition1;
    public byte Condition2;
    public uint CollisionMask1;
    public uint CollisionMask2;
    public uint CollisionMask3;
    public uint CollisionMask4;
    public uint CollisionMask5;
    public uint CollisionMask6;
    public uint CollisionMask7;
    public uint CollisionMask8;
    public uint CollisionMask9;
    public uint CollisionMask10;
    public uint CollisionMask11;
    public uint CollisionMask12;
    public uint CollisionMask13;
    public uint CollisionMask14;
    public uint CollisionMask15;
    public uint CollisionMask16;
    public uint CollisionMask17;
    public uint CollisionMask18;
    public uint CollisionMask19;
    public uint CollisionMask20;
    public uint CollisionMask21;
    public uint CollisionMask22;
    public uint CollisionMask23;
    public uint CollisionMask24;
    public uint CollisionMask25;
    public uint CollisionMask26;
    public uint CollisionMask27;
    public uint CollisionMask28;
    public uint CollisionMask29;
    public uint CollisionMask30;
    public uint CollisionMask31;
    public uint CollisionMask32;
    public uint CollisionMask33;
    public uint CollisionMask34;
    public uint CollisionMask35;
    public uint CollisionMask36;
    public uint CollisionMask37;
    public uint CollisionMask38;
    public uint CollisionMask39;
    public uint CollisionMask40;
    public uint CollisionMask41;
    public uint CollisionMask42;
    public uint CollisionMask43;
    public uint CollisionMask44;
    public uint CollisionMask45;
    public uint CollisionMask46;
    public uint CollisionMask47;
    public uint CollisionMask48;


    public void setStruct(MSBS.Part.UnkStruct1 part)
    {
        Condition1 = part.Condition1;
        Condition2 = part.Condition2;
        CollisionMask1 = part.CollisionMask[0];
        CollisionMask2 = part.CollisionMask[1];
        CollisionMask3 = part.CollisionMask[2];
        CollisionMask4 = part.CollisionMask[3];
        CollisionMask5 = part.CollisionMask[4];
        CollisionMask6 = part.CollisionMask[5];
        CollisionMask7 = part.CollisionMask[6];
        CollisionMask8 = part.CollisionMask[7];
        CollisionMask9 = part.CollisionMask[8];
        CollisionMask10 = part.CollisionMask[9];
        CollisionMask11 = part.CollisionMask[10];
        CollisionMask12 = part.CollisionMask[11];
        CollisionMask13 = part.CollisionMask[12];
        CollisionMask14 = part.CollisionMask[13];
        CollisionMask15 = part.CollisionMask[14];
        CollisionMask16 = part.CollisionMask[15];
        CollisionMask17 = part.CollisionMask[16];
        CollisionMask18 = part.CollisionMask[17];
        CollisionMask19 = part.CollisionMask[18];
        CollisionMask20 = part.CollisionMask[19];
        CollisionMask21 = part.CollisionMask[20];
        CollisionMask22 = part.CollisionMask[21];
        CollisionMask23 = part.CollisionMask[22];
        CollisionMask24 = part.CollisionMask[23];
        CollisionMask25 = part.CollisionMask[24];
        CollisionMask26 = part.CollisionMask[25];
        CollisionMask27 = part.CollisionMask[26];
        CollisionMask28 = part.CollisionMask[27];
        CollisionMask29 = part.CollisionMask[28];
        CollisionMask30 = part.CollisionMask[29];
        CollisionMask31 = part.CollisionMask[30];
        CollisionMask32 = part.CollisionMask[31];
        CollisionMask33 = part.CollisionMask[32];
        CollisionMask34 = part.CollisionMask[33];
        CollisionMask35 = part.CollisionMask[34];
        CollisionMask36 = part.CollisionMask[35];
        CollisionMask37 = part.CollisionMask[36];
        CollisionMask38 = part.CollisionMask[37];
        CollisionMask39 = part.CollisionMask[38];
        CollisionMask40 = part.CollisionMask[39];
        CollisionMask41 = part.CollisionMask[40];
        CollisionMask42 = part.CollisionMask[41];
        CollisionMask43 = part.CollisionMask[42];
        CollisionMask44 = part.CollisionMask[43];
        CollisionMask45 = part.CollisionMask[44];
        CollisionMask46 = part.CollisionMask[45];
        CollisionMask47 = part.CollisionMask[46];
        CollisionMask48 = part.CollisionMask[47];
    }

    
    public MSBS.Part.UnkStruct1 Serialize()
    {
        MSBS.Part.UnkStruct1 part = new MSBS.Part.UnkStruct1();
        part.Condition1 = Condition1;
        part.Condition2 = Condition2;
        part.CollisionMask[0] = CollisionMask1;
        part.CollisionMask[1] = CollisionMask2;
        part.CollisionMask[2] = CollisionMask3;
        part.CollisionMask[3] = CollisionMask4;
        part.CollisionMask[4] = CollisionMask5;
        part.CollisionMask[5] = CollisionMask6;
        part.CollisionMask[6] = CollisionMask7;
        part.CollisionMask[7] = CollisionMask8;
        part.CollisionMask[8] = CollisionMask9;
        part.CollisionMask[9] = CollisionMask10;
        part.CollisionMask[10] = CollisionMask11;
        part.CollisionMask[11] = CollisionMask12;
        part.CollisionMask[12] = CollisionMask13;
        part.CollisionMask[13] = CollisionMask14;
        part.CollisionMask[14] = CollisionMask15;
        part.CollisionMask[15] = CollisionMask16;
        part.CollisionMask[16] = CollisionMask17;
        part.CollisionMask[17] = CollisionMask18;
        part.CollisionMask[18] = CollisionMask19;
        part.CollisionMask[19] = CollisionMask20;
        part.CollisionMask[20] = CollisionMask21;
        part.CollisionMask[21] = CollisionMask22;
        part.CollisionMask[22] = CollisionMask23;
        part.CollisionMask[23] = CollisionMask24;
        part.CollisionMask[24] = CollisionMask25;
        part.CollisionMask[25] = CollisionMask26;
        part.CollisionMask[26] = CollisionMask27;
        part.CollisionMask[27] = CollisionMask28;
        part.CollisionMask[28] = CollisionMask29;
        part.CollisionMask[29] = CollisionMask30;
        part.CollisionMask[30] = CollisionMask31;
        part.CollisionMask[31] = CollisionMask32;
        part.CollisionMask[32] = CollisionMask33;
        part.CollisionMask[33] = CollisionMask34;
        part.CollisionMask[34] = CollisionMask35;
        part.CollisionMask[35] = CollisionMask36;
        part.CollisionMask[36] = CollisionMask37;
        part.CollisionMask[37] = CollisionMask38;
        part.CollisionMask[38] = CollisionMask39;
        part.CollisionMask[39] = CollisionMask40;
        part.CollisionMask[40] = CollisionMask41;
        part.CollisionMask[41] = CollisionMask42;
        part.CollisionMask[42] = CollisionMask43;
        part.CollisionMask[43] = CollisionMask44;
        part.CollisionMask[44] = CollisionMask45;
        part.CollisionMask[45] = CollisionMask46;
        part.CollisionMask[46] = CollisionMask47;
        part.CollisionMask[47] = CollisionMask48;
        return part;
    }
}
