using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MeowDSIO.DataTypes.FMG
{
    public enum VanillaFMG
    {
        ArmourDescriptions,
        ArmourDescriptions_Patch,
        ArmourNames,
        ArmourNames_Patch,
        ArmourSummaries,
        ArmourSummaries_Patch,
        BloodMessages,
        BloodMessages_Patch,
        ContextualHelp,
        Conversations,
        Conversations_Patch,
        DebugTags_Win32,
        EventTexts,
        EventTexts_Patch,
        FeatureDescriptions,
        FeatureNames,
        FeatureSummaries,
        IngameMenus,
        ItemDescriptions,
        ItemDescriptions_Patch,
        ItemNames,
        ItemNames_Patch,
        ItemSummaries,
        ItemSummaries_Patch,
        KeyGuide,
        KeyGuide_Patch,
        MenuDialogs,
        MenuDialogs_Patch,
        MenuHelpSnippets,
        MenuHelpSnippets_Patch,
        MenuText_Common,
        MenuText_Common_Patch,
        MenuText_Other,
        MenuText_Other_Patch,
        MovieSubtitles,
        NPCNames,
        NPCNames_Patch,
        PlaceNames,
        PlaceNames_Patch,
        RingDescriptions,
        RingDescriptions_Patch,
        RingNames,
        RingNames_Patch,
        RingSummaries,
        RingSummaries_Patch,
        SpellDescriptions,
        SpellDescriptions_Patch,
        SpellNames,
        SpellNames_Patch,
        SpellSummaries,
        SystemMessages_Win32,
        SystemMessages_Win32_Patch,
        TextTagPlaceholders,
        WeaponDescriptions,
        WeaponDescriptions_Patch,
        WeaponNames,
        WeaponNames_Patch,
        WeaponSummaries,
        WeaponSummaries_Patch,
    }
}
